// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingRequest) Reset() {
	*x = TrendingRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingRequest) ProtoMessage() {}

func (x *TrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingRequest.ProtoReflect.Descriptor instead.
func (*TrendingRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TrendingRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *TrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TrendingTopic       `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingResponse) Reset() {
	*x = TrendingResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingResponse) ProtoMessage() {}

func (x *TrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingResponse.ProtoReflect.Descriptor instead.
func (*TrendingResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TrendingResponse) GetTopics() []*TrendingTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TrendingTopic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	TrendScore    float32                `protobuf:"fixed32,3,opt,name=trend_score,json=trendScore,proto3" json:"trend_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingTopic) Reset() {
	*x = TrendingTopic{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingTopic) ProtoMessage() {}

func (x *TrendingTopic) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingTopic.ProtoReflect.Descriptor instead.
func (*TrendingTopic) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *TrendingTopic) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *TrendingTopic) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *TrendingTopic) GetTrendScore() float32 {
	if x != nil {
		return x.TrendScore
	}
	return 0
}

type QualityRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ArticleId    string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Market       string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	QualityScore float32                `protobuf:"fixed32,3,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	// Token + model captured at LLM call site (agent), forwarded to analytics
	// for cost computation. Added 2026-05-21 (Phase K1 cost tracking).
	PromptTokens     int32  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Model            string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QualityRequest) Reset() {
	*x = QualityRequest{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityRequest) ProtoMessage() {}

func (x *QualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityRequest.ProtoReflect.Descriptor instead.
func (*QualityRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *QualityRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *QualityRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *QualityRequest) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *QualityRequest) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *QualityRequest) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *QualityRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type QualityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recorded      bool                   `protobuf:"varint,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityResponse) Reset() {
	*x = QualityResponse{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityResponse) ProtoMessage() {}

func (x *QualityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityResponse.ProtoReflect.Descriptor instead.
func (*QualityResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *QualityResponse) GetRecorded() bool {
	if x != nil {
		return x.Recorded
	}
	return false
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\x15newsroom.analytics.v1\"?\n" +
	"\x0fTrendingRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"P\n" +
	"\x10TrendingResponse\x12<\n" +
	"\x06topics\x18\x01 \x03(\v2$.newsroom.analytics.v1.TrendingTopicR\x06topics\"j\n" +
	"\rTrendingTopic\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x1f\n" +
	"\vtrend_score\x18\x03 \x01(\x02R\n" +
	"trendScore\"\xd4\x01\n" +
	"\x0eQualityRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12#\n" +
	"\rquality_score\x18\x03 \x01(\x02R\fqualityScore\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x05R\x10completionTokens\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\"-\n" +
	"\x0fQualityResponse\x12\x1a\n" +
	"\brecorded\x18\x01 \x01(\bR\brecorded2\xde\x01\n" +
	"\x10AnalyticsService\x12e\n" +
	"\x12GetTrendingSignals\x12&.newsroom.analytics.v1.TrendingRequest\x1a'.newsroom.analytics.v1.TrendingResponse\x12c\n" +
	"\x12RecordQualityScore\x12%.newsroom.analytics.v1.QualityRequest\x1a&.newsroom.analytics.v1.QualityResponseB4Z2github.com/newsroom/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analytics_proto_goTypes = []any{
	(*TrendingRequest)(nil),  // 0: newsroom.analytics.v1.TrendingRequest
	(*TrendingResponse)(nil), // 1: newsroom.analytics.v1.TrendingResponse
	(*TrendingTopic)(nil),    // 2: newsroom.analytics.v1.TrendingTopic
	(*QualityRequest)(nil),   // 3: newsroom.analytics.v1.QualityRequest
	(*QualityResponse)(nil),  // 4: newsroom.analytics.v1.QualityResponse
}
var file_analytics_proto_depIdxs = []int32{
	2, // 0: newsroom.analytics.v1.TrendingResponse.topics:type_name -> newsroom.analytics.v1.TrendingTopic
	0, // 1: newsroom.analytics.v1.AnalyticsService.GetTrendingSignals:input_type -> newsroom.analytics.v1.TrendingRequest
	3, // 2: newsroom.analytics.v1.AnalyticsService.RecordQualityScore:input_type -> newsroom.analytics.v1.QualityRequest
	1, // 3: newsroom.analytics.v1.AnalyticsService.GetTrendingSignals:output_type -> newsroom.analytics.v1.TrendingResponse
	4, // 4: newsroom.analytics.v1.AnalyticsService.RecordQualityScore:output_type -> newsroom.analytics.v1.QualityResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
