DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS edges;
DROP TABLE IF EXISTS performance;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS journalists;
DROP TABLE IF EXISTS casbin_rule;
DROP TABLE IF EXISTS users;
