// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: learner.proto

package learnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LearnerService_QueryKnowledgeGraph_FullMethodName  = "/newsroom.learner.v1.LearnerService/QueryKnowledgeGraph"
	LearnerService_GetJournalistProfile_FullMethodName = "/newsroom.learner.v1.LearnerService/GetJournalistProfile"
	LearnerService_ScoreFactualAccuracy_FullMethodName = "/newsroom.learner.v1.LearnerService/ScoreFactualAccuracy"
	LearnerService_GetTopicSuggestions_FullMethodName  = "/newsroom.learner.v1.LearnerService/GetTopicSuggestions"
)

// LearnerServiceClient is the client API for LearnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Called by Agent (context fetch), Moderation (factual accuracy check), and Frontend (editorial suggestions).
type LearnerServiceClient interface {
	QueryKnowledgeGraph(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	GetJournalistProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	ScoreFactualAccuracy(ctx context.Context, in *FactualRequest, opts ...grpc.CallOption) (*FactualResponse, error)
	GetTopicSuggestions(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error)
}

type learnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearnerServiceClient(cc grpc.ClientConnInterface) LearnerServiceClient {
	return &learnerServiceClient{cc}
}

func (c *learnerServiceClient) QueryKnowledgeGraph(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LearnerService_QueryKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnerServiceClient) GetJournalistProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, LearnerService_GetJournalistProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnerServiceClient) ScoreFactualAccuracy(ctx context.Context, in *FactualRequest, opts ...grpc.CallOption) (*FactualResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactualResponse)
	err := c.cc.Invoke(ctx, LearnerService_ScoreFactualAccuracy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learnerServiceClient) GetTopicSuggestions(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestionsResponse)
	err := c.cc.Invoke(ctx, LearnerService_GetTopicSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearnerServiceServer is the server API for LearnerService service.
// All implementations must embed UnimplementedLearnerServiceServer
// for forward compatibility.
//
// Called by Agent (context fetch), Moderation (factual accuracy check), and Frontend (editorial suggestions).
type LearnerServiceServer interface {
	QueryKnowledgeGraph(context.Context, *QueryRequest) (*QueryResponse, error)
	GetJournalistProfile(context.Context, *ProfileRequest) (*ProfileResponse, error)
	ScoreFactualAccuracy(context.Context, *FactualRequest) (*FactualResponse, error)
	GetTopicSuggestions(context.Context, *SuggestionsRequest) (*SuggestionsResponse, error)
	mustEmbedUnimplementedLearnerServiceServer()
}

// UnimplementedLearnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLearnerServiceServer struct{}

func (UnimplementedLearnerServiceServer) QueryKnowledgeGraph(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryKnowledgeGraph not implemented")
}
func (UnimplementedLearnerServiceServer) GetJournalistProfile(context.Context, *ProfileRequest) (*ProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJournalistProfile not implemented")
}
func (UnimplementedLearnerServiceServer) ScoreFactualAccuracy(context.Context, *FactualRequest) (*FactualResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoreFactualAccuracy not implemented")
}
func (UnimplementedLearnerServiceServer) GetTopicSuggestions(context.Context, *SuggestionsRequest) (*SuggestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopicSuggestions not implemented")
}
func (UnimplementedLearnerServiceServer) mustEmbedUnimplementedLearnerServiceServer() {}
func (UnimplementedLearnerServiceServer) testEmbeddedByValue()                        {}

// UnsafeLearnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearnerServiceServer will
// result in compilation errors.
type UnsafeLearnerServiceServer interface {
	mustEmbedUnimplementedLearnerServiceServer()
}

func RegisterLearnerServiceServer(s grpc.ServiceRegistrar, srv LearnerServiceServer) {
	// If the following call panics, it indicates UnimplementedLearnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LearnerService_ServiceDesc, srv)
}

func _LearnerService_QueryKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnerServiceServer).QueryKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnerService_QueryKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnerServiceServer).QueryKnowledgeGraph(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnerService_GetJournalistProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnerServiceServer).GetJournalistProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnerService_GetJournalistProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnerServiceServer).GetJournalistProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnerService_ScoreFactualAccuracy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnerServiceServer).ScoreFactualAccuracy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnerService_ScoreFactualAccuracy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnerServiceServer).ScoreFactualAccuracy(ctx, req.(*FactualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearnerService_GetTopicSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearnerServiceServer).GetTopicSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearnerService_GetTopicSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearnerServiceServer).GetTopicSuggestions(ctx, req.(*SuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LearnerService_ServiceDesc is the grpc.ServiceDesc for LearnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newsroom.learner.v1.LearnerService",
	HandlerType: (*LearnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryKnowledgeGraph",
			Handler:    _LearnerService_QueryKnowledgeGraph_Handler,
		},
		{
			MethodName: "GetJournalistProfile",
			Handler:    _LearnerService_GetJournalistProfile_Handler,
		},
		{
			MethodName: "ScoreFactualAccuracy",
			Handler:    _LearnerService_ScoreFactualAccuracy_Handler,
		},
		{
			MethodName: "GetTopicSuggestions",
			Handler:    _LearnerService_GetTopicSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learner.proto",
}
