// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: learner.proto

package learnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_learner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*KnowledgeNode       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_learner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetNodes() []*KnowledgeNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type KnowledgeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // journalist | article | topic
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeNode) Reset() {
	*x = KnowledgeNode{}
	mi := &file_learner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeNode) ProtoMessage() {}

func (x *KnowledgeNode) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeNode.ProtoReflect.Descriptor instead.
func (*KnowledgeNode) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{2}
}

func (x *KnowledgeNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KnowledgeNode) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeNode) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JournalistId  string                 `protobuf:"bytes,1,opt,name=journalist_id,json=journalistId,proto3" json:"journalist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_learner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileRequest) GetJournalistId() string {
	if x != nil {
		return x.JournalistId
	}
	return ""
}

type ProfileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JournalistId   string                 `protobuf:"bytes,1,opt,name=journalist_id,json=journalistId,proto3" json:"journalist_id,omitempty"`
	Market         string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Specialization string                 `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	StyleProfile   []byte                 `protobuf:"bytes,4,opt,name=style_profile,json=styleProfile,proto3" json:"style_profile,omitempty"` // JSON-encoded JSONB
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_learner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileResponse) GetJournalistId() string {
	if x != nil {
		return x.JournalistId
	}
	return ""
}

func (x *ProfileResponse) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *ProfileResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *ProfileResponse) GetStyleProfile() []byte {
	if x != nil {
		return x.StyleProfile
	}
	return nil
}

type FactualRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactualRequest) Reset() {
	*x = FactualRequest{}
	mi := &file_learner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactualRequest) ProtoMessage() {}

func (x *FactualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactualRequest.ProtoReflect.Descriptor instead.
func (*FactualRequest) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{5}
}

func (x *FactualRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *FactualRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FactualResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccuracyScore float32                `protobuf:"fixed32,1,opt,name=accuracy_score,json=accuracyScore,proto3" json:"accuracy_score,omitempty"` // 0.0 – 1.0
	Issues        []string               `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactualResponse) Reset() {
	*x = FactualResponse{}
	mi := &file_learner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactualResponse) ProtoMessage() {}

func (x *FactualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactualResponse.ProtoReflect.Descriptor instead.
func (*FactualResponse) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{6}
}

func (x *FactualResponse) GetAccuracyScore() float32 {
	if x != nil {
		return x.AccuracyScore
	}
	return 0
}

func (x *FactualResponse) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

type SuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsRequest) Reset() {
	*x = SuggestionsRequest{}
	mi := &file_learner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsRequest) ProtoMessage() {}

func (x *SuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsRequest.ProtoReflect.Descriptor instead.
func (*SuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestionsRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *SuggestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopicSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	SourceCount   int32                  `protobuf:"varint,3,opt,name=source_count,json=sourceCount,proto3" json:"source_count,omitempty"`
	ExampleUrls   []string               `protobuf:"bytes,4,rep,name=example_urls,json=exampleUrls,proto3" json:"example_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicSuggestion) Reset() {
	*x = TopicSuggestion{}
	mi := &file_learner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSuggestion) ProtoMessage() {}

func (x *TopicSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSuggestion.ProtoReflect.Descriptor instead.
func (*TopicSuggestion) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{8}
}

func (x *TopicSuggestion) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *TopicSuggestion) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *TopicSuggestion) GetSourceCount() int32 {
	if x != nil {
		return x.SourceCount
	}
	return 0
}

func (x *TopicSuggestion) GetExampleUrls() []string {
	if x != nil {
		return x.ExampleUrls
	}
	return nil
}

type SuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []*TopicSuggestion     `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsResponse) Reset() {
	*x = SuggestionsResponse{}
	mi := &file_learner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsResponse) ProtoMessage() {}

func (x *SuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsResponse.ProtoReflect.Descriptor instead.
func (*SuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_learner_proto_rawDescGZIP(), []int{9}
}

func (x *SuggestionsResponse) GetSuggestions() []*TopicSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_learner_proto protoreflect.FileDescriptor

const file_learner_proto_rawDesc = "" +
	"\n" +
	"\rlearner.proto\x12\x13newsroom.learner.v1\"R\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"I\n" +
	"\rQueryResponse\x128\n" +
	"\x05nodes\x18\x01 \x03(\v2\".newsroom.learner.v1.KnowledgeNodeR\x05nodes\"e\n" +
	"\rKnowledgeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\"5\n" +
	"\x0eProfileRequest\x12#\n" +
	"\rjournalist_id\x18\x01 \x01(\tR\fjournalistId\"\x9b\x01\n" +
	"\x0fProfileResponse\x12#\n" +
	"\rjournalist_id\x18\x01 \x01(\tR\fjournalistId\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12&\n" +
	"\x0especialization\x18\x03 \x01(\tR\x0especialization\x12#\n" +
	"\rstyle_profile\x18\x04 \x01(\fR\fstyleProfile\"B\n" +
	"\x0eFactualRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"P\n" +
	"\x0fFactualResponse\x12%\n" +
	"\x0eaccuracy_score\x18\x01 \x01(\x02R\raccuracyScore\x12\x16\n" +
	"\x06issues\x18\x02 \x03(\tR\x06issues\"B\n" +
	"\x12SuggestionsRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x91\x01\n" +
	"\x0fTopicSuggestion\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12!\n" +
	"\fsource_count\x18\x03 \x01(\x05R\vsourceCount\x12!\n" +
	"\fexample_urls\x18\x04 \x03(\tR\vexampleUrls\"]\n" +
	"\x13SuggestionsResponse\x12F\n" +
	"\vsuggestions\x18\x01 \x03(\v2$.newsroom.learner.v1.TopicSuggestionR\vsuggestions2\x9e\x03\n" +
	"\x0eLearnerService\x12\\\n" +
	"\x13QueryKnowledgeGraph\x12!.newsroom.learner.v1.QueryRequest\x1a\".newsroom.learner.v1.QueryResponse\x12a\n" +
	"\x14GetJournalistProfile\x12#.newsroom.learner.v1.ProfileRequest\x1a$.newsroom.learner.v1.ProfileResponse\x12a\n" +
	"\x14ScoreFactualAccuracy\x12#.newsroom.learner.v1.FactualRequest\x1a$.newsroom.learner.v1.FactualResponse\x12h\n" +
	"\x13GetTopicSuggestions\x12'.newsroom.learner.v1.SuggestionsRequest\x1a(.newsroom.learner.v1.SuggestionsResponseB\xba\x01\n" +
	"\x17com.newsroom.learner.v1B\fLearnerProtoP\x01Z#github.com/newsroom/proto;learnerv1\xa2\x02\x03NLX\xaa\x02\x13Newsroom.Learner.V1\xca\x02\x13Newsroom\\Learner\\V1\xe2\x02\x1fNewsroom\\Learner\\V1\\GPBMetadata\xea\x02\x15Newsroom::Learner::V1b\x06proto3"

var (
	file_learner_proto_rawDescOnce sync.Once
	file_learner_proto_rawDescData []byte
)

func file_learner_proto_rawDescGZIP() []byte {
	file_learner_proto_rawDescOnce.Do(func() {
		file_learner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learner_proto_rawDesc), len(file_learner_proto_rawDesc)))
	})
	return file_learner_proto_rawDescData
}

var file_learner_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_learner_proto_goTypes = []any{
	(*QueryRequest)(nil),        // 0: newsroom.learner.v1.QueryRequest
	(*QueryResponse)(nil),       // 1: newsroom.learner.v1.QueryResponse
	(*KnowledgeNode)(nil),       // 2: newsroom.learner.v1.KnowledgeNode
	(*ProfileRequest)(nil),      // 3: newsroom.learner.v1.ProfileRequest
	(*ProfileResponse)(nil),     // 4: newsroom.learner.v1.ProfileResponse
	(*FactualRequest)(nil),      // 5: newsroom.learner.v1.FactualRequest
	(*FactualResponse)(nil),     // 6: newsroom.learner.v1.FactualResponse
	(*SuggestionsRequest)(nil),  // 7: newsroom.learner.v1.SuggestionsRequest
	(*TopicSuggestion)(nil),     // 8: newsroom.learner.v1.TopicSuggestion
	(*SuggestionsResponse)(nil), // 9: newsroom.learner.v1.SuggestionsResponse
}
var file_learner_proto_depIdxs = []int32{
	2, // 0: newsroom.learner.v1.QueryResponse.nodes:type_name -> newsroom.learner.v1.KnowledgeNode
	8, // 1: newsroom.learner.v1.SuggestionsResponse.suggestions:type_name -> newsroom.learner.v1.TopicSuggestion
	0, // 2: newsroom.learner.v1.LearnerService.QueryKnowledgeGraph:input_type -> newsroom.learner.v1.QueryRequest
	3, // 3: newsroom.learner.v1.LearnerService.GetJournalistProfile:input_type -> newsroom.learner.v1.ProfileRequest
	5, // 4: newsroom.learner.v1.LearnerService.ScoreFactualAccuracy:input_type -> newsroom.learner.v1.FactualRequest
	7, // 5: newsroom.learner.v1.LearnerService.GetTopicSuggestions:input_type -> newsroom.learner.v1.SuggestionsRequest
	1, // 6: newsroom.learner.v1.LearnerService.QueryKnowledgeGraph:output_type -> newsroom.learner.v1.QueryResponse
	4, // 7: newsroom.learner.v1.LearnerService.GetJournalistProfile:output_type -> newsroom.learner.v1.ProfileResponse
	6, // 8: newsroom.learner.v1.LearnerService.ScoreFactualAccuracy:output_type -> newsroom.learner.v1.FactualResponse
	9, // 9: newsroom.learner.v1.LearnerService.GetTopicSuggestions:output_type -> newsroom.learner.v1.SuggestionsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_learner_proto_init() }
func file_learner_proto_init() {
	if File_learner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learner_proto_rawDesc), len(file_learner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learner_proto_goTypes,
		DependencyIndexes: file_learner_proto_depIdxs,
		MessageInfos:      file_learner_proto_msgTypes,
	}.Build()
	File_learner_proto = out.File
	file_learner_proto_goTypes = nil
	file_learner_proto_depIdxs = nil
}
