# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import learner_pb2 as learner__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in learner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearnerServiceStub(object):
    """Called by Agent (context fetch) and Moderation (factual accuracy check).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryKnowledgeGraph = channel.unary_unary(
                '/newsroom.learner.v1.LearnerService/QueryKnowledgeGraph',
                request_serializer=learner__pb2.QueryRequest.SerializeToString,
                response_deserializer=learner__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.GetJournalistProfile = channel.unary_unary(
                '/newsroom.learner.v1.LearnerService/GetJournalistProfile',
                request_serializer=learner__pb2.ProfileRequest.SerializeToString,
                response_deserializer=learner__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.ScoreFactualAccuracy = channel.unary_unary(
                '/newsroom.learner.v1.LearnerService/ScoreFactualAccuracy',
                request_serializer=learner__pb2.FactualRequest.SerializeToString,
                response_deserializer=learner__pb2.FactualResponse.FromString,
                _registered_method=True)


class LearnerServiceServicer(object):
    """Called by Agent (context fetch) and Moderation (factual accuracy check).
    """

    def QueryKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJournalistProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreFactualAccuracy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryKnowledgeGraph,
                    request_deserializer=learner__pb2.QueryRequest.FromString,
                    response_serializer=learner__pb2.QueryResponse.SerializeToString,
            ),
            'GetJournalistProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJournalistProfile,
                    request_deserializer=learner__pb2.ProfileRequest.FromString,
                    response_serializer=learner__pb2.ProfileResponse.SerializeToString,
            ),
            'ScoreFactualAccuracy': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreFactualAccuracy,
                    request_deserializer=learner__pb2.FactualRequest.FromString,
                    response_serializer=learner__pb2.FactualResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'newsroom.learner.v1.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('newsroom.learner.v1.LearnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearnerService(object):
    """Called by Agent (context fetch) and Moderation (factual accuracy check).
    """

    @staticmethod
    def QueryKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/newsroom.learner.v1.LearnerService/QueryKnowledgeGraph',
            learner__pb2.QueryRequest.SerializeToString,
            learner__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJournalistProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/newsroom.learner.v1.LearnerService/GetJournalistProfile',
            learner__pb2.ProfileRequest.SerializeToString,
            learner__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreFactualAccuracy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/newsroom.learner.v1.LearnerService/ScoreFactualAccuracy',
            learner__pb2.FactualRequest.SerializeToString,
            learner__pb2.FactualResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
