# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: learner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'learner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlearner.proto\x12\x13newsroom.learner.v1\"<\n\x0cQueryRequest\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"B\n\rQueryResponse\x12\x31\n\x05nodes\x18\x01 \x03(\x0b\x32\".newsroom.learner.v1.KnowledgeNode\"J\n\rKnowledgeNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06weight\x18\x04 \x01(\x02\"\'\n\x0eProfileRequest\x12\x15\n\rjournalist_id\x18\x01 \x01(\t\"g\n\x0fProfileResponse\x12\x15\n\rjournalist_id\x18\x01 \x01(\t\x12\x0e\n\x06market\x18\x02 \x01(\t\x12\x16\n\x0especialization\x18\x03 \x01(\t\x12\x15\n\rstyle_profile\x18\x04 \x01(\x0c\"1\n\x0e\x46\x61\x63tualRequest\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"9\n\x0f\x46\x61\x63tualResponse\x12\x16\n\x0e\x61\x63\x63uracy_score\x18\x01 \x01(\x02\x12\x0e\n\x06issues\x18\x02 \x03(\t2\xb4\x02\n\x0eLearnerService\x12\\\n\x13QueryKnowledgeGraph\x12!.newsroom.learner.v1.QueryRequest\x1a\".newsroom.learner.v1.QueryResponse\x12\x61\n\x14GetJournalistProfile\x12#.newsroom.learner.v1.ProfileRequest\x1a$.newsroom.learner.v1.ProfileResponse\x12\x61\n\x14ScoreFactualAccuracy\x12#.newsroom.learner.v1.FactualRequest\x1a$.newsroom.learner.v1.FactualResponseB0Z.github.com/newsroom/proto/learner/v1;learnerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'learner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/newsroom/proto/learner/v1;learnerv1'
  _globals['_QUERYREQUEST']._serialized_start=38
  _globals['_QUERYREQUEST']._serialized_end=98
  _globals['_QUERYRESPONSE']._serialized_start=100
  _globals['_QUERYRESPONSE']._serialized_end=166
  _globals['_KNOWLEDGENODE']._serialized_start=168
  _globals['_KNOWLEDGENODE']._serialized_end=242
  _globals['_PROFILEREQUEST']._serialized_start=244
  _globals['_PROFILEREQUEST']._serialized_end=283
  _globals['_PROFILERESPONSE']._serialized_start=285
  _globals['_PROFILERESPONSE']._serialized_end=388
  _globals['_FACTUALREQUEST']._serialized_start=390
  _globals['_FACTUALREQUEST']._serialized_end=439
  _globals['_FACTUALRESPONSE']._serialized_start=441
  _globals['_FACTUALRESPONSE']._serialized_end=498
  _globals['_LEARNERSERVICE']._serialized_start=501
  _globals['_LEARNERSERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
